### ISSUE TITLE
Website Model Bugs

### ISSUE THREAD

**Issue by CarsonDavis** [NASA-IMPACT/admg-backend#237]
# General Notes
After the recent updates to the website model structure, several bugs and areas for improvement have been identified.

## Failed Migration
- original migration failed to run entirely
- this was corrected, but the migration script still appears to be lacking
- when you look at the change objects, there are some with model_name UNKNOWN. these are the original CampaignWebsites which need to be deleted

## Publishing Websites
- when you go to publish a website it returns
- {'url': [ErrorDetail(string='Enter a valid URL.', code='invalid')]}
- http://admgstaging.nasa-impact.net/drafts/edit/7a8d2952-15d3-4c3d-a73f-40e83415c11c/transition
- other models are unaffected

## Campaign Page
- existing websites do not appear in the websites section 
- newly created websites appear

## Website View
- there exists no place to view a list of all websites

## Website Filters
 - when searching for a website, the search fails because short_name is not a search field
example
- website should filter on title, and probably campaign

## API
- websites are missing from the json response of campaign

# Tasks
- [x] fix migration script, such that existing websites appear
- [x] figure out why websites can't publish
- [x] add a view for websites
- [x] add a menu item for websites
- [x] add a filter for title in the website view
- [x] add a filter for campaign in the website view (optional)
- [x] add related reference to camp from web
- [x] add websites to serializers
