### ISSUE TITLE
EPIC: MI Workflow Enhancement - Release 1

### ISSUE THREAD

**Issue by sowmyasub** [NASA-IMPACT/admg-backend#270]
_Update Aug 25, 2022 with proposed stories and process documentation_

### Problem
- The current maintenance interface design reflects how the data model works where everything is a record/draft. 
- For example, a `create` campaign draft or an `update` instrument draft. 
- As more drafts are added over time and update are created, the **number of drafts that are part of the same “family” gets harder to keep track of** because it’s all shown in one table.
-  While being able to reference past records can be nice, it’s not the same level of importance. 

### Goal
- **Improve curator workflow for finding, updating, and keeping track of published and edit drafts.** 
- To a curator, we learned that the most important information is what is currently published, and whether or not there is an edit to that published version. 
- The scope is for campaigns, instruments, and platforms (not the limited fields, partner organization page) as they represent the main data categories.

### Designs  
- [Figma 80% completed designs](https://www.figma.com/proto/zY7BS9fR1huZ0CieHf3Dm8/CASEI-MI---Workflow-Redesign?page-id=175%3A26643&node-id=175%3A27057&viewport=523%2C172%2C0.02&scaling=scale-down&starting-point-node-id=175%3A27057&show-proto-sidebar=1)
- [Figma working file](https://www.figma.com/file/zY7BS9fR1huZ0CieHf3Dm8/MI-Workflow-Change?node-id=175%3A26643) (Consider these 80% done as things will change during implementation)
- [Reference design process documentation](https://github.com/NASA-IMPACT/admg-backend/blob/dev/adr/0003-workflow-redesign-process.md)

## Development
https://github.com/NASA-IMPACT/admg-backend/pull/437

## User Requirements (not development stories)
The following stories will be used to track completion of the overall work. They are written from a user requirement standpoint, not technical steps. The actual development stories will be created during development and we will close out the user requirement stories as they are demoed in a staging environment.

- [x] [Discuss approach to branch strategy for this epic #390](https://github.com/NASA-IMPACT/admg-backend/issues/390)
- [x] [Only allow one edit draft at a time #375](https://github.com/NASA-IMPACT/admg-backend/issues/375)

**Campaign Dashboard**
- [x] [Consolidate versions of a campaign into a Dashboard view #376](https://github.com/NASA-IMPACT/admg-backend/issues/376)
  - [x] [Dashboard-Published Tab: Display latest published campaigns #377](https://github.com/NASA-IMPACT/admg-backend/issues/377)
  - [x] [Dashboard-Edit Tab: Display current updates #378](https://github.com/NASA-IMPACT/admg-backend/issues/378)
  - [ ]  [Campaign Dashboard-Details: Deployments #380](https://github.com/NASA-IMPACT/admg-backend/issues/380)
  - [ ]  [Campaign Dashboard-Details: IOPs #391](https://github.com/NASA-IMPACT/admg-backend/issues/391)
  - [ ]  [Campaign Dashboard-Details: Significant Events #392](https://github.com/NASA-IMPACT/admg-backend/issues/392)
  - [ ]  [Campaign Dashboard-Details: CDPIs #393](https://github.com/NASA-IMPACT/admg-backend/issues/393)
  - [ ] [Campaign Dashboard-DOIs: Display DOI recommendations #381](https://github.com/NASA-IMPACT/admg-backend/issues/381)
  - [x] [Campaign Dashboard-History: Display past versions and associations #382](https://github.com/NASA-IMPACT/admg-backend/issues/382)
      - [ ] [Auto-naming history change summary #398](https://github.com/NASA-IMPACT/admg-backend/issues/398)
- [x] [Campaign home table links to Dashboard view #379](https://github.com/NASA-IMPACT/admg-backend/issues/379)
- [x] [Remove Campaign Items page navigation #394](https://github.com/NASA-IMPACT/admg-backend/issues/394)

**Platform Dashboard**
- [x] [Consolidate versions of a Platform into a Dashboard view #383](https://github.com/NASA-IMPACT/admg-backend/issues/383)
- [x] [Platform home table links to Dashboard view #384](https://github.com/NASA-IMPACT/admg-backend/issues/384)

**Instrument Dashboard**
- [x] [Consolidate versions of a Instrument into a Dashboard view #385](https://github.com/NASA-IMPACT/admg-backend/issues/385)
- [x] [Instruments home table links to Dashboard view #386](https://github.com/NASA-IMPACT/admg-backend/issues/386)

**Other**
- [ ] [Clean Up Sidebar UI #276](https://github.com/NASA-IMPACT/admg-backend/issues/276)
- [x] [Create Status Tracker #304](https://github.com/NASA-IMPACT/admg-backend/issues/304)
