### ISSUE TITLE
Housekeeping: Clean up repo and branches

### ISSUE THREAD

**Issue by EJwalker13** [NASA-IMPACT/admg-backend#435]
## Overview
The admg-backend currently contains 46 branches from the master branch. As best practice, we need to go in and clean each branch along with anything in the back-end repo.

### Branches
Read the code, see if it's linked to an open/backlogged issue. 

### Issues
Contact whoever created the issue, or maybe heidi.

### Users
Gather list of users on the repo from the Security tab. Send this list to Heidi and Stephanie and ask them which ones can be removed.

## Tasks
- [ ] clean up old branches
- [ ] clean up old issues
- [ ] remove old users on repo who should no longer have access
