### ISSUE TITLE
EPIC: MI Workflow Enhancement - Future Roadmap

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-backend#461]
## Context
A project to update the **MI workflow** to improve the curator experience was implemented in FY23.Q2. 
### EPIC: MI Workflow Enhancement - Release 1  https://github.com/NASA-IMPACT/admg-backend/issues/270

As part of this we:
- Created a single “family” or “canonical id” for campaigns, platforms, and instruments so that it only needs to be displayed once at summary level
- Removed the campaign items at main nav level in favor of accessing that information within the context of a campaign. 
- Redirected all campaigns, platforms, and instruments to a single dashboard view which shows you the latest published draft AND latest edits (if any) as subtabs.
- Created a new history tab within a given campaign dashboard is where historical drafts live. 

## Future Roadmap

- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/380
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/391
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/392
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/393
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/381
- [x] #398
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/276

**Comment by heidimok** [comment]
Closing this issue as we have released the new MI workflow and do not plan to make these additional changes.
