### ISSUE TITLE
Documentation: Sphinx and Read the Docs

### ISSUE THREAD

**Issue by praveenphatate** [NASA-IMPACT/admg-backend#477]
## Overview
After meeting with Ed, he recommended some tools to use for writing documentation. Two of the tools he recommended were Sphinx and Read the Docs. We plan to utilize these tools to produce structured documents referenced from our code.
### Sphinx
Sphinx is a tool which uses Python Doc strings to create a HTML style page for the documentation
### Read the Docs
Read the Docs is an open-source documentation platform that allows developers to build, host, and automatically generate documentation for their projects

### Tasks
- [x] Create a django app with Sphinx
- [x] Create it on our project
- [x] Push to the Test Server
