### ISSUE TITLE
Documentation: Main Github Readme file

### ISSUE THREAD

**Issue by praveenphatate** [NASA-IMPACT/admg-backend#478]
### Overview
The main readme file will be the first page on github project. This document is meant to be an index not the actual documentation page. This document will only direct users to the specific documentation files which uses links.

### Tasks
- [x] Explain CASEI
- [x] Link API documentation
- [x] List the contents of the repository
- [x] List the contents of "How to run the repo on user's end?"
- [x] Testing the code in the repo
- [x] Add documents to Sphinx
