### ISSUE TITLE
Host documentation on github pages

### ISSUE THREAD

**Issue by EJwalker13** [NASA-IMPACT/admg-backend#484]
### Overview
ADMG has made major progress towards documentation. Currently, the documentation has been edited into a better format with Sphinx and Django. Now we want to host the documentation online and on the github repo as a step to finalize this effort.

### Tasks
- [x] Add sphinx to ADMG project
- [x] Get it up and running online
- [x] Host documentation on github
