### ISSUE TITLE
EPIC: Finalize DOIs

### ISSUE THREAD

**Issue by CarsonDavis** [NASA-IMPACT/admg-backend#502]
### Branch merging and code review
- [x] look at the new branch made by ed (doi merge?)
    - does it pass the tests on its own branch?
    - do the changes make sense?
- [x] merge this branch into the new test branch
   - do all the tests pass?
 
### Deployment
- [x] merge remove ed into dev
- [x] deploy to staging using procedure from other card

### Clean up
- [ ] delete duplicate dois (where is this code?)
- [ ] figure out what's going on with the missing concept_ids on old update drafts
- [ ] figure out why some published DOIs are missing data

### Supplementation
- [ ] run the supplementation code
