### ISSUE TITLE
Epic: Open Source the Project

### ISSUE THREAD

**Issue by CarsonDavis** [NASA-IMPACT/admg-backend#518]
Open sourcing the project consists of filing NTR paperwork and some small tasks to bring the repo up to snuff with licenses and credentials. 

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/521
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/560
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/592
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/599
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/593
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/594
```
