### ISSUE TITLE
Update Repo to Address Open Source Requirements

### ISSUE THREAD

**Issue by CarsonDavis** [NASA-IMPACT/admg-backend#528]
On this card, we need to hold off on changing the repo settings to public until the NTRS paperwork is fully approved.

```[tasklist]
### Tasks
- [ ] Change the repo license to Apache v2
- [ ] double check there are no credentials/account ids in the repo.
- [ ] get a review from Iksha
- [ ] change the repo settings to public
```
