### ISSUE TITLE
MI workflow issues from testing are resolved and deployed into production

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-backend#537]
## Context
In Jan-April 2023, we release the first set of changes for a new maintenance interface workflow in order to help curators better keep track of all the change drafts related to a campaign, platform, and instrument over time. See epic: https://github.com/NASA-IMPACT/admg-backend/issues/270. The first release before/after are documented [here](https://docs.google.com/presentation/d/1J1oNKWjkKAflfUHF7xQmksHYEBNP-T3firVtY0Dner8/edit#slide=id.gb700de37bd_0_149). Things that we left out were consolidated into a new issue for the future [here](https://github.com/NASA-IMPACT/admg-backend/issues/461).

## Problem
The updated workflow is sitting in the [test environment](https://admgdev.nasa-impact.net/) not yet deployed. We don't want to deploy until curators have tested it because of the significant changes. However, keeping it in test is creating problems over time because issues in the current production are being reported that might not be relevant once we have these changes merged. Also there is end to end testing in this version but not the one currently in production.

## Acceptance Criteria
- [x] Curators have tested out the MI changes in the test environment https://github.com/NASA-IMPACT/ADMG-project/issues/792
- [x] Curators have reported issues [here](https://docs.google.com/document/d/1X6w2rd4j-6IRvS6mhxfSNZl1Rw_XLVz5nV9rYXxc1kA/edit#heading=h.q68bajwoy63c)
- [x] Issues relevant to the workflow changes have been created and address
- [x] The updated MI workflow has been deployed from test to staging and then production
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/548
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/549
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/550
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/551
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/552
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/553
- [ ] https://github.com/NASA-IMPACT/admg-backend/issues/555
```
